// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $AboutMe from "./islands/AboutMe.tsx";
import * as $Commands from "./islands/Commands.tsx";
import * as $ErrorPage from "./islands/ErrorPage.tsx";
import * as $Fact from "./islands/Fact.tsx";
import * as $Loading from "./islands/Loading.tsx";
import * as $welcome from "./islands/welcome.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/AboutMe.tsx": $AboutMe,
    "./islands/Commands.tsx": $Commands,
    "./islands/ErrorPage.tsx": $ErrorPage,
    "./islands/Fact.tsx": $Fact,
    "./islands/Loading.tsx": $Loading,
    "./islands/welcome.tsx": $welcome,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
